apiVersion: apps/v1
kind: Deployment
metadata:
  name: clouds-deployment
  labels:
    app: clouds
spec:
  replicas: 3
  selector:
    matchLabels:
      app: clouds
  template:
    metadata:
      labels:
        app: clouds
    spec:
      containers:
      - name: clouds
        image: vaibhavduggal/radha:latest
        ports:
        - containerPort: 4200

