name: next git

on:
  push:
    branches: ['main']

jobs:
  run-app:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ---------------- FRONTEND ----------------
      - name: Install frontend
        run: npm install
        working-directory: frontend-kiza

      - name: Start frontend with PM2
        run: |
          pm2 delete angular-front || true
          pm2 start npm --name angular-front -- run start -- --host 0.0.0.0 --port 4200
          pm2 save
        working-directory: frontend-kiza

      # ---------------- BACKEND ----------------
      - name: Install backend
        run: npm install
        working-directory: backend

      - name: Start backend with PM2
        run: |
          pm2 delete node-backend || true
          pm2 start index.js --name node-backend
          pm2 save
        working-directory: backend
