name: next git docker

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.IP }}
          username: karan
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd /home/karan/projectfront

            # update latest code
            git pull origin main
            npm install 
            npm run build 
            npm i http-server -g 
            sudo npm i pm2 -g 
            pm2 delete frontend
            pm2 start http-server --name frontend -- dist/projectfront -p 4200
