name: first git

on:
  push:
    branches:
      - main

jobs:
  run-app:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - run: docker rm -f kunj || true

      - run: docker build -t kunj .

      - run: docker run -d --name kunj -p 4200:4200 kunj
